language: php

php:
  - 5.4
  - 5.5

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install --prefer-source --dev --no-interaction
 - cd tests

script:
 - ../vendor/bin/phpunit
